services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
      
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:16.3-bullseye
    hostname: backend-db
    environment:
      POSTGRES_PASSWORD: "backend"
      POSTGRES_USER: "backend"
      POSTGRES_DB: "backend"
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U backend
      interval: 2s
      timeout: 3s
      retries: 40


volumes:
  backend-db-data:
    name: backend-db-data
