services:
  frontend:
    build:
      dockerfile: .devcontainer/Dockerfile.dev
    ports:
      # Exposes application port.
    - 5100:5173
    - 4100:4173
    volumes:
      # Adds current directory as volume.
    - ./frontend:/app
    command: sleep infinity
  backend:
    build:
      dockerfile: .devcontainer/Dockerfile.dev
    ports:
      # Exposes application port.
    - 8000:8000
    volumes:
      # Adds current directory as volume.
    - ./backend:/app
    command: sleep infinity
    environment:
      # Enables autoreload.
      BACKEND_RELOAD: "True"
