apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  POSTGRES_USER: dbuser
  POSTGRES_PASSWORD: dbpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://dbuser:dbpassword@postgres-db/backend
  PASSWORD_SECRET_SALT: thI5iSaStr0ngS4lt
