apiVersion: v2
name: inventory-app
description: A Helm chart for my inventory application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgres
    version: 1.0.0
    repository: file://charts/postgres