replicaCount: 1

frontend:
  image:
    repository: ghcr.io/savvasmohito/pa2577-assignment1-frontend
    tag: "1.0"
  service:
    port: 3000
  env:
    BACKEND_URL: http://backend:8000
    ORIGIN: http://10.68.123.139:32000

backend:
  image:
    repository: ghcr.io/savvasmohito/pa2577-assignment1-backend
    tag: "1.0"
  service:
    port: 8000

postgres:
  image:
    repository: postgres
    tag: "16.3-bullseye"
  env:
    POSTGRES_DB: backend
  storage:
    accessMode: ReadWriteMany
    size: 1Gi
